import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import ModuleTabs from "@/components/shared/ModuleTabs";
import { salesTabs } from "./SalesDashboard";
import { Download, FileText } from "lucide-react";

export default function SalesReports() {
  return (
    <div className="space-y-4">
      <h1 className="text-xl font-semibold" data-testid="text-page-title">Sales and Invoicing</h1>
      <ModuleTabs tabs={salesTabs} />
      
      <div className="flex justify-between items-center mt-4">
        <h2 className="text-lg font-medium">Reports</h2>
      </div>
      
      <div className="grid gap-4 md:grid-cols-2 lg:grid-cols-3">
        {[
          { name: "Monthly Sales Report", desc: "Overview of all sales for the month", type: "PDF" },
          { name: "Customer Analysis", desc: "Top customers by revenue", type: "Excel" },
          { name: "Invoice Aging Report", desc: "Outstanding invoices by age", type: "PDF" },
          { name: "Product Performance", desc: "Best selling products analysis", type: "Excel" },
          { name: "Revenue Forecast", desc: "Projected revenue for next quarter", type: "PDF" },
          { name: "Commission Report", desc: "Sales team commission breakdown", type: "Excel" },
        ].map((report, i) => (
          <Card key={i} className="hover-elevate cursor-pointer">
            <CardHeader className="flex flex-row items-start justify-between gap-2 space-y-0 pb-2">
              <div className="flex items-center gap-3">
                <FileText className="h-8 w-8 text-primary" />
                <div>
                  <CardTitle className="text-sm font-medium">{report.name}</CardTitle>
                  <p className="text-xs text-muted-foreground mt-1">{report.desc}</p>
                </div>
              </div>
            </CardHeader>
            <CardContent>
              <div className="flex justify-between items-center">
                <span className="text-xs text-muted-foreground">{report.type}</span>
                <Button size="sm" variant="outline" data-testid={`button-download-${i}`}>
                  <Download className="h-3 w-3 mr-1" />
                  Download
                </Button>
              </div>
            </CardContent>
          </Card>
        ))}
      </div>
      
      <Card>
        <CardHeader>
          <CardTitle className="text-base">Recent Reports</CardTitle>
        </CardHeader>
        <CardContent>
          <div className="overflow-x-auto">
            <table className="w-full text-sm">
              <thead>
                <tr className="border-b">
                  <th className="text-left py-2 px-2">Report Name</th>
                  <th className="text-left py-2 px-2">Generated</th>
                  <th className="text-left py-2 px-2">Generated By</th>
                  <th className="text-left py-2 px-2">Type</th>
                  <th className="text-left py-2 px-2">Action</th>
                </tr>
              </thead>
              <tbody>
                {[
                  { name: "Monthly Sales - Dec 2025", date: "2026-01-02", by: "Admin", type: "PDF" },
                  { name: "Customer Analysis Q4", date: "2026-01-01", by: "John Smith", type: "Excel" },
                  { name: "Invoice Aging - Dec 2025", date: "2025-12-31", by: "Admin", type: "PDF" },
                ].map((row, i) => (
                  <tr key={i} className="border-b hover:bg-muted/50">
                    <td className="py-2 px-2">{row.name}</td>
                    <td className="py-2 px-2">{row.date}</td>
                    <td className="py-2 px-2">{row.by}</td>
                    <td className="py-2 px-2">{row.type}</td>
                    <td className="py-2 px-2">
                      <Button size="sm" variant="ghost">
                        <Download className="h-3 w-3" />
                      </Button>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </CardContent>
      </Card>
    </div>
  );
}
